/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/uploads/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Csv */
        post: operations["upload_csv_api_uploads_csv_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads/xlsx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Xlsx */
        post: operations["upload_xlsx_api_uploads_xlsx_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Snapshots */
        get: operations["listar_snapshots_api_snapshots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshots/{snapshot_id}/debitos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Debitos */
        get: operations["listar_debitos_api_snapshots__snapshot_id__debitos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comparisons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter Comparacao */
        get: operations["obter_comparacao_api_comparisons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter Dashboard */
        get: operations["obter_dashboard_api_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matching-issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter Pendencias Pareamento */
        get: operations["obter_pendencias_pareamento_api_matching_issues_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Entidades */
        get: operations["listar_entidades_api_entities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities/{entidade_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter Entidade */
        get: operations["obter_entidade_api_entities__entidade_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exports/{dataset}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Exportar Dataset */
        get: operations["exportar_dataset_api_exports__dataset__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_csv_api_uploads_csv_post */
        Body_upload_csv_api_uploads_csv_post: {
            /**
             * Arquivo
             * Format: binary
             */
            arquivo: string;
        };
        /** Body_upload_xlsx_api_uploads_xlsx_post */
        Body_upload_xlsx_api_uploads_xlsx_post: {
            /**
             * Arquivo
             * Format: binary
             */
            arquivo: string;
        };
        /** ComparacaoOut */
        ComparacaoOut: {
            resumo: components["schemas"]["ResumoComparacaoOut"];
            /** Entidades Somente Csv */
            entidades_somente_csv: components["schemas"]["EntidadeResumoOut"][];
            /** Entidades Somente Xlsx */
            entidades_somente_xlsx: components["schemas"]["EntidadeResumoOut"][];
            /** Obrigacoes Somente Csv */
            obrigacoes_somente_csv: components["schemas"]["ObrigacaoExclusivaOut"][];
            /** Obrigacoes Somente Xlsx */
            obrigacoes_somente_xlsx: components["schemas"]["ObrigacaoExclusivaOut"][];
            /** Conflitos Parcelamento */
            conflitos_parcelamento: components["schemas"]["ConflitoParcelamentoOut"][];
            /** Nomes Ambiguos */
            nomes_ambiguos: components["schemas"]["NomeAmbiguoOut"][];
        };
        /** ConflitoParcelamentoOut */
        ConflitoParcelamentoOut: {
            entidade: components["schemas"]["EntidadeResumoOut"];
            /** Ano Referencia */
            ano_referencia: number;
            /** Tipo Debito */
            tipo_debito: string;
            /** Parcelado Csv */
            parcelado_csv: boolean;
            /** Parcelado Xlsx */
            parcelado_xlsx: boolean;
        };
        /** DashboardOut */
        DashboardOut: {
            indicadores: components["schemas"]["IndicadoresDashboardOut"];
            /** Ranking Obrigacoes */
            ranking_obrigacoes: components["schemas"]["RankingObrigacoesItemOut"][];
            /** Ranking Valor Total */
            ranking_valor_total: components["schemas"]["RankingValorTotalItemOut"][];
            /** Divida Ativa */
            divida_ativa: components["schemas"]["DebitoDividaAtivaOut"][];
            /** Distribuicao Ano */
            distribuicao_ano: components["schemas"]["DistribuicaoAnoOut"][];
            /** Distribuicao Tipo */
            distribuicao_tipo: components["schemas"]["DistribuicaoTipoOut"][];
            /** Distribuicao Situacao Pagamento */
            distribuicao_situacao_pagamento: components["schemas"]["DistribuicaoSituacaoPagamentoOut"][];
            /** Distribuicao Situacao Cadastral */
            distribuicao_situacao_cadastral: components["schemas"]["DistribuicaoSituacaoCadastralOut"][];
            /** Serie Historica Xlsx */
            serie_historica_xlsx: components["schemas"]["PontoSerieHistoricaOut"][];
        };
        /** DebitoDividaAtivaOut */
        DebitoDividaAtivaOut: {
            entidade: components["schemas"]["EntidadeResumoOut"];
            /** Ano Referencia */
            ano_referencia: number;
            /** Tipo Debito */
            tipo_debito: string;
            /** Situacao Divida Ativa */
            situacao_divida_ativa: string;
            /** Valor Total */
            valor_total: string | null;
        };
        /** DebitoHistoricoOut */
        DebitoHistoricoOut: {
            /** Id */
            id: number;
            /** Snapshot Id */
            snapshot_id: number;
            /**
             * Data Snapshot
             * Format: date-time
             */
            data_snapshot: string;
            /** Origem */
            origem: string;
            /** Ano Referencia */
            ano_referencia: number;
            /** Tipo Debito */
            tipo_debito: string;
            /** Numero Parcela */
            numero_parcela: number | null;
            /** Data Vencimento */
            data_vencimento: string | null;
            /** Valor Original */
            valor_original: string | null;
            /** Valor Devido */
            valor_devido: string | null;
            /** Valor Total */
            valor_total: string | null;
            /** Situacao Pagamento */
            situacao_pagamento: string | null;
            /** Situacao Divida Ativa */
            situacao_divida_ativa: string | null;
            /** Situacao Parcelamento */
            situacao_parcelamento: string | null;
        };
        /** DebitoOut */
        DebitoOut: {
            /** Id */
            id: number;
            /** Origem */
            origem: string;
            /** Ano Referencia */
            ano_referencia: number;
            /** Tipo Debito */
            tipo_debito: string;
            /** Numero Parcela */
            numero_parcela: number | null;
            /** Data Vencimento */
            data_vencimento: string | null;
            /** Valor Original */
            valor_original: number | null;
            /** Valor Devido */
            valor_devido: number | null;
            /** Valor Total */
            valor_total: number | null;
            /** Situacao Pagamento */
            situacao_pagamento: string | null;
            /** Situacao Divida Ativa */
            situacao_divida_ativa: string | null;
            /** Situacao Parcelamento */
            situacao_parcelamento: string | null;
            entidade: components["schemas"]["EntidadeResumoOut"];
        };
        /** DistribuicaoAnoOut */
        DistribuicaoAnoOut: {
            /** Ano Referencia */
            ano_referencia: number;
            /** Quantidade */
            quantidade: number;
            /** Valor Total */
            valor_total: string;
        };
        /**
         * DistribuicaoSituacaoCadastralOut
         * @description Situacao cadastral (ObservacaoEntidade.situacao_registro) cruzada com a existencia de
         *     debito em aberto no snapshot XLSX escolhido -- ex.: profissionais BAIXADOS que ainda
         *     possuem divida pendente (spec story 18).
         */
        DistribuicaoSituacaoCadastralOut: {
            /** Situacao Registro */
            situacao_registro: string;
            /** Total Entidades */
            total_entidades: number;
            /** Total Com Debito Aberto */
            total_com_debito_aberto: number;
            /** Total Sem Debito Aberto */
            total_sem_debito_aberto: number;
        };
        /** DistribuicaoSituacaoPagamentoOut */
        DistribuicaoSituacaoPagamentoOut: {
            /** Situacao Pagamento */
            situacao_pagamento: string;
            /** Quantidade */
            quantidade: number;
            /** Valor Total */
            valor_total: string;
        };
        /** DistribuicaoTipoOut */
        DistribuicaoTipoOut: {
            /** Tipo Debito */
            tipo_debito: string;
            /** Quantidade */
            quantidade: number;
            /** Valor Total */
            valor_total: string;
        };
        /** EntidadeDetalheOut */
        EntidadeDetalheOut: {
            entidade: components["schemas"]["EntidadeResumoOut"];
            /** Observacoes */
            observacoes: components["schemas"]["ObservacaoHistoricoOut"][];
            /** Debitos */
            debitos: components["schemas"]["DebitoHistoricoOut"][];
        };
        /** EntidadeResumoOut */
        EntidadeResumoOut: {
            /** Id */
            id: number | null;
            /** Observacao Id */
            observacao_id: number;
            /** Nome Normalizado */
            nome_normalizado: string;
            /** Nome Original */
            nome_original: string;
            /** Cpf Cnpj */
            cpf_cnpj: string | null;
            /** Tipo Pessoa */
            tipo_pessoa: string | null;
            /** Registro Resumido */
            registro_resumido: string | null;
            /** Categoria */
            categoria: string | null;
            /** Subregiao */
            subregiao: string | null;
            /** Situacao Registro */
            situacao_registro: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IndicadoresDashboardOut */
        IndicadoresDashboardOut: {
            /** Csv Snapshot Id */
            csv_snapshot_id: number;
            /** Xlsx Snapshot Id */
            xlsx_snapshot_id: number;
            /** Total Entidades Xlsx */
            total_entidades_xlsx: number;
            /** Total Obrigacoes Distintas Xlsx */
            total_obrigacoes_distintas_xlsx: number;
            /** Total Valor Total Xlsx */
            total_valor_total_xlsx: string;
            /** Total Parcelas Em Aberto Csv */
            total_parcelas_em_aberto_csv: number;
            /** Total Debitos Divida Ativa */
            total_debitos_divida_ativa: number;
            /** Total Debitos Divida Ativa Executiva */
            total_debitos_divida_ativa_executiva: number;
        };
        /** NomeAmbiguoOut */
        NomeAmbiguoOut: {
            /** Nome Normalizado */
            nome_normalizado: string;
            nome_csv: components["schemas"]["EntidadeResumoOut"];
            /** Candidatos Xlsx */
            candidatos_xlsx: components["schemas"]["EntidadeResumoOut"][];
        };
        /** ObrigacaoExclusivaOut */
        ObrigacaoExclusivaOut: {
            entidade: components["schemas"]["EntidadeResumoOut"];
            /** Ano Referencia */
            ano_referencia: number;
            /** Tipo Debito */
            tipo_debito: string;
        };
        /** ObservacaoHistoricoOut */
        ObservacaoHistoricoOut: {
            /** Snapshot Id */
            snapshot_id: number;
            /** Tipo Arquivo */
            tipo_arquivo: string;
            /**
             * Data Snapshot
             * Format: date-time
             */
            data_snapshot: string;
            /** Observacao Id */
            observacao_id: number;
            /** Nome Original */
            nome_original: string;
            /** Nome Normalizado */
            nome_normalizado: string;
            /** Cpf Cnpj */
            cpf_cnpj: string | null;
            /** Tipo Pessoa */
            tipo_pessoa: string | null;
            /** Registro Resumido */
            registro_resumido: string | null;
            /** Categoria */
            categoria: string | null;
            /** Subregiao */
            subregiao: string | null;
            /** Situacao Registro */
            situacao_registro: string | null;
        };
        /** PaginaDebitosOut */
        PaginaDebitosOut: {
            /** Items */
            items: components["schemas"]["DebitoOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Pages */
            pages: number;
        };
        /** PaginaEntidadesOut */
        PaginaEntidadesOut: {
            /** Items */
            items: components["schemas"]["EntidadeResumoOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Pages */
            pages: number;
        };
        /**
         * PendenciasPareamentoOut
         * @description Pendencias de pareamento (spec story 22): nomes que nao bateram exatamente
         *     entre CSV e XLSX no par de snapshots selecionado, para revisao manual.
         */
        PendenciasPareamentoOut: {
            /** Csv Snapshot Id */
            csv_snapshot_id: number;
            /** Xlsx Snapshot Id */
            xlsx_snapshot_id: number;
            /** Somente Csv */
            somente_csv: components["schemas"]["EntidadeResumoOut"][];
            /** Somente Xlsx */
            somente_xlsx: components["schemas"]["EntidadeResumoOut"][];
            /** Nomes Ambiguos */
            nomes_ambiguos: components["schemas"]["NomeAmbiguoOut"][];
        };
        /** PontoSerieHistoricaOut */
        PontoSerieHistoricaOut: {
            /** Snapshot Id */
            snapshot_id: number;
            /**
             * Data Snapshot
             * Format: date-time
             */
            data_snapshot: string;
            /** Total Entidades */
            total_entidades: number;
            /** Total Valor Total */
            total_valor_total: string;
            /** Total Divida Ativa */
            total_divida_ativa: number;
        };
        /** RankingObrigacoesItemOut */
        RankingObrigacoesItemOut: {
            entidade: components["schemas"]["EntidadeResumoOut"];
            /** Total Obrigacoes */
            total_obrigacoes: number;
        };
        /** RankingValorTotalItemOut */
        RankingValorTotalItemOut: {
            entidade: components["schemas"]["EntidadeResumoOut"];
            /** Valor Total */
            valor_total: string;
        };
        /** ResumoComparacaoOut */
        ResumoComparacaoOut: {
            /** Csv Snapshot Id */
            csv_snapshot_id: number;
            /** Xlsx Snapshot Id */
            xlsx_snapshot_id: number;
            /** Total Csv */
            total_csv: number;
            /** Total Xlsx */
            total_xlsx: number;
            /** Total Pareados */
            total_pareados: number;
            /** Total Somente Csv */
            total_somente_csv: number;
            /** Total Somente Xlsx */
            total_somente_xlsx: number;
            /** Total Nomes Ambiguos */
            total_nomes_ambiguos: number;
            /** Total Obrigacoes Somente Csv */
            total_obrigacoes_somente_csv: number;
            /** Total Obrigacoes Somente Xlsx */
            total_obrigacoes_somente_xlsx: number;
            /** Total Conflitos Parcelamento */
            total_conflitos_parcelamento: number;
        };
        /** SnapshotOut */
        SnapshotOut: {
            /** Id */
            id: number;
            /** Tipo Arquivo */
            tipo_arquivo: string;
            /** Nome Arquivo Original */
            nome_arquivo_original: string;
            /**
             * Data Snapshot
             * Format: date-time
             */
            data_snapshot: string;
            /**
             * Data Upload
             * Format: date-time
             */
            data_upload: string;
            /**
             * Linhas Invalidas
             * @default []
             */
            linhas_invalidas: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    upload_csv_api_uploads_csv_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_csv_api_uploads_csv_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_xlsx_api_uploads_xlsx_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_xlsx_api_uploads_xlsx_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_snapshots_api_snapshots_get: {
        parameters: {
            query?: {
                tipo_arquivo?: ("csv" | "xlsx") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_debitos_api_snapshots__snapshot_id__debitos_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                snapshot_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaDebitosOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obter_comparacao_api_comparisons_get: {
        parameters: {
            query?: {
                csv_snapshot_id?: number | null;
                xlsx_snapshot_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparacaoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obter_dashboard_api_dashboard_get: {
        parameters: {
            query?: {
                csv_snapshot_id?: number | null;
                xlsx_snapshot_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obter_pendencias_pareamento_api_matching_issues_get: {
        parameters: {
            query?: {
                csv_snapshot_id?: number | null;
                xlsx_snapshot_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendenciasPareamentoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_entidades_api_entities_get: {
        parameters: {
            query?: {
                query?: string | null;
                tipo_pessoa?: string | null;
                situacao_registro?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaEntidadesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obter_entidade_api_entities__entidade_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entidade_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntidadeDetalheOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    exportar_dataset_api_exports__dataset__get: {
        parameters: {
            query?: {
                format?: "csv" | "xlsx";
                csv_snapshot_id?: number | null;
                xlsx_snapshot_id?: number | null;
                query?: string | null;
                tipo_pessoa?: string | null;
                situacao_registro?: string | null;
            };
            header?: never;
            path: {
                dataset: "ranking" | "comparisons" | "entities" | "matching-issues";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
